  name: CI/CD auth-service
  on:
    push:
      branches: ["develop","release/**"]
      paths:
      - 'auth-service/**'
      - '.github/workflows/ci-auth-service.yml'
  permissions:
   id-token: write
   contents: read
   security-events: write
   actions: read
  jobs:
   buildci:
    name: build and push
    uses: ./.github/workflows/_java-build.yml
    with:
     project: pharma
     environments: dev
     servicedir: auth-service
   deploy:
    name: deploy to dev
    needs: buildci
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
       repository:  hemanthrajgandham/zen-gitops
       token: "${{secrets.GITOPS_TOKEN}}"
       path: _gitops
    - name: get image tag
       
      run: echo "${{needs.build.outputs.IMAGE_NUMBER}}"
        
    
   
  
 
