name: deploy to dev
on:
  push: 
   branches:
    ["develop","release/**"]
   paths:
   - 'auth-service/**'
   - '.github/workflows/ci.auth-service.yml'
permissions:
 id-token: write
 contents: read
 security-events: write
 actions: read
jobs:
 buildandpush:
   name: full ci
   uses: "./.github/workflows/_java-build.yml"
   with:
    project: pharma
    environments: dev
    servicedir: auth-service
   secrets: inherit
 deploytodev:
   runs-on: ubuntu:latest
   needs: buildandpush
   steps:
   - name: print the image number
     run: echo "${{needs.buildandpush.outputs.IMAGE_NUMBER}}"     
   - name: checkout the gitops
     uses: actions/checkout@v4
     with:
      reference: hemanthrajgandham/gitops
      path: _gitops
      token: "${{secrets.GITOPS_TOKEN}}"
