name: cicd pipeline
on:
 workflow_dispatch:
   inputs:
     environments:
       type: choice       
       options:
         - dev
         - qa
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup java
        uses: actions/setup-java@v5
        with:
         distribution: 'temurin'
         java-version: '25'
         cache: 'maven'
         
      - name: integration testing
        run: |
         cd auth-services
         mvn verify 
         
         
