name: hemanth cicd pipeline
on:
 push:
  branches: ["main"]
permissions: 
 contents: read
 id-token: write
 security-events: write
jobs:
  build:
   runs-on: ubuntu-22.04
   outputs:
     imagenumber: ${{steps.imagenumber.outputs.image_sha}}
   steps:
    - name: checkout code
      uses: actions/checkout@v5
    - name: setup java
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
        
    - name: get the github run number
      id: imagenumber
      run: |
        IMAGE_NUMBER="${GITHUB_SHA::7}" 
        echo image_sha="sha-${IMAGE_NUMBER}">> $GITHUB_OUTPUT
    - name: print number
      run: echo "${{steps.imagenumber.outputs.image_sha}}"
    - name: codeql install
      uses: github/codeql-action/init@v5
      with:
       languages: java
    - name: build
      run: |
        cd auth-service
        mvn verify
    - name: upload
      uses: actions/upload-artifact@v5
      with:
        name: authservice
        path: auth-service/target
    - name: analyze codeql
      uses: github/codeql-action/analyze@v5
      continue-on-error: false
      with:
       severity: HIGH,CRITICAL
  
      
      
   


  
